apiVersion: apps/v1
kind: Deployment
metadata:
  name: pplcid
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pplcid
  template:
    metadata:
      labels:
        app: pplcid
    spec:
      containers:
      - name: pplcid
        image: pplcid/did-base:latest
        ports:
        - containerPort: 3000
        env:
          - name: LANG
            value: C.UTF-8
          - name: RAILS_LOG_TO_STDOUT
            value: "TRUE"
          - name: RAILS_SERVE_STATIC_FILES
            value: "TRUE"
          - name: RAILS_ENV
            value: production
          - name: DB_HOST
            value: db-cluster-postgresql.default.svc.cluster.local
          - name: DB_NAME
            value: ppldid_production
          - name: DB_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pplcid-secrets
                key: db-passwd
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: pplcid-secrets
                key: secret-key-base