apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ppldid
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - ppldid.ppldid.peopledata.org.cn
    secretName: ppldid-tls
  rules:
  - host: ppldid.ppldid.peopledata.org.cn
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: ppldid
            port:
              number: 80
